#/*
# * Copyright (c) 2018 JP-L, https://www.jp-l.org/
# *
# * Permission is hereby granted, free of charge, to any person obtaining
# * a copy of this software and associated documentation files (the
# * "Software"), to deal in the Software without restriction, including
# * without limitation the rights to use, copy, modify, merge, publish,
# * distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so, subject to
# * the following conditions:
# *
# * The above copyright notice and this permission notice shall be
# * included in all copies or substantial portions of the Software.
#
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#*/

# Language setting
language: java

# Set language version. This is only required if you use the default Shippable image for your build
jdk:
  - oraclejdk8

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    #- master
    - releases
    - development

# Specify which services you need. This is only valid if you use the default Shippable image for your build
#services:

env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/src/test
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/

#matrix:

# The build configuration
build:
  # commands in this section run on your build machine and not inside your CI container.
  pre_ci:
    - echo "==== Prepare environment ====" &&
      mkdir -p $TEST_RESULTS_DIR && 
      mkdir -p $CODE_COVERAGE_DIR && 
      pushd $TESTS_LOC_DIR;
      if [ "$BRANCH" == "development" ]; then
           echo "==== Development branch ====";
      elif [ "$BRANCH" == "release" ]; then
           echo "==== Release branch ====";
      elif [ "$BRANCH" == "master" ]; then
           echo "==== Master branch ====";
      else
           echo "==== Unknown branch ====";
      fi
    #- echo "==== Kill any old containers which might be running ====" && docker ps -a | grep -v 'reqProc' | cut -d ' ' -f1 #| xargs docker stop"
    #- echo "==== DEBUG List all environment variables ====" && printenv

  pre_ci_boot:
    image_name: $CI_CONTAINER
    image_tag: $CI_CONTAINER_VERSION
    pull: true
    options: '--privileged=false --net=bridge -e FOO=true -e BOO=false'

  # commands in this section run inside your CI container. In addition, any commands such as ls, 
  # in this section can be used to skip default processing for CI.
  ci:
    - chmod +x $SHIPPABLE_REPO_DIR/bas/scripts/shippable/*
    - $SHIPPABLE_REPO_DIR/bas/scripts/shippable/prepare.sh 
        -src $SHIPPABLE_REPO_DIR/bas/resources/gradle/gradle.properties 
        $DEBUG
    - $SHIPPABLE_REPO_DIR/bas/scripts/shippable/package.sh 
        $DEBUG
    - echo "==== CI completed. Move to post CI ===="

  post_ci:
    - $SHIPPABLE_REPO_DIR/bas/scripts/shippable/finalize.sh -p

  on_success:
    - $SHIPPABLE_REPO_DIR/bas/scripts/shippable/finalize.sh -s

  on_failure:
    - $SHIPPABLE_REPO_DIR/bas/scripts/shippable/finalize.sh -f
    
  cache: false

integrations:
# If you are using integrations, you'll need to set it up in two places. Subscription settings & here in this section of the yml.
    notifications:
        - integrationName: Slack
          type: slack
          recipients:
            - "#jdemo"
          branches:
            only:
                - master
                - release
                - development
          on_success: always
          on_failure: always
          on_pull_request: always
          on_start: always

    hub:
        - integrationName: AWS-EIS
          type: ecr
          region: eu-west-1
#          agent_only:
#          branches:

    generic:     
        - integrationName: Sonar
        - integrationName: BRep
        - integrationName: SRep
    
#### END CI CONFIG

#### RESOURCES CONFIG (GLOBAL ACROSS SUBSCRIPTION)
resources:
    # Params
    - name: CI_CONTAINER
      type: params
      versionTemplate:
        params:
          secure: QRrl5lPJ3n81QyeeC0fEYzmDxwEBjjJizBsuqTIbWql7nndDrsjdnGxNyHS/qzFmLbVCoCRspCG6Wv3BsQ9GSZ0qwfMK8MdPdexsjZL/PNCusRQT0yyqiVRMF+jfo212+zmjxRFqvVvHU4VDSNAy0CTk1gKlIocL4FafveveYLB6lZDy8rtfVjnU8YeXcT5vXKyX6n6jh3YNGmAjhqzSgKI3QjEiil0dRCLpJrra5BCOao7A46Lbk/21heD7MJeMg28BTfwJ+yKDBIeFp/OS+kXl4O83nUgvVElF4ECb4/70tgxInX+WeVAs0GRVBO4UZnkmt11kIA2gOLCg0M7ZCQ==

    - name: CI_CONTAINER_VERSION
      type: params
      versionTemplate:
        params:
          CI_CONTAINER_VERSION: '1.0'
    
    - name: IMAGE
      type: params
      versionTemplate:
        params:
          secure: QeuzsKzHkuajVJZRzot2eMFbi5yxqjsdsSkOfVoPU8vS5GWeZkK9aUyvUSxPiQVSstDXJhifFYlrTFJ9zwkvjReSpEKd7Yq0OyX+aLFG7oLmqxplyqUIQcM77pEguBRO2ohQnu0j838RZW3xvQc1CBYfvINEorDPF+hVti9T96oS+E2XRVGo3b+HYLAMQ0jjj8LDetDSK/rEHRhcjNh0YLWHemrBelwr114EtPLdqsharqSPdwsTPhQMYjZdnrOemEg7yfCxku+br7ZHudgKCWL+jpxPWrn3zR0CRlYSlVc/YDYycjU9EPRNZgwO3hXBBxDOkzAykUHjvF3R/Sotkg==

    - name: IMAGE_VERSION
      type: params
      versionTemplate:
        params:
          IMAGE_VERSION: 'latest'

    # Job resources
    - name: scripts-from-srcRepo
      type: gitRepo
      integration: GitHub
      versionTemplate:
        sourceName: "JP-L/jdemo"
        branch: "releases"
    
    - name: jdemoImg
      type: image
      integration: AWS-EIS
      versionTemplate:
        sourceName: $IMAGE_REPOSITORY
        versionName: $IMAGE_VERSION
        
    - name: jdemoImgQA
      type: image
      integration: AWS-EIS
      versionTemplate:
        sourceName: $IMAGE_REPOSITORY
        versionName: $IMAGE_VERSION

     # Docker options
    - name: dockerOptions
      type: dockerOptions
      versionTemplate:
        memory: 1024                        #in MiB
        #cpuShares: 10
        portMappings:
            - "80:8080/tcp"
        logConfig:
            type: awslogs
            options:
              awslogs-group: /var/log/docker
              awslogs-region: eu-central-1
              awslogs-stream-prefix: jdemo
        privileged: false                     # May be true or false

    # Number of replicas
    - name: replicas
      type: replicas
      versionTemplate:
        count: 1
        
    # Cluster
    - name: EUC1-QA-cluster
      type: cluster
      integration: AWS-EIS
      versionTemplate:
        sourceName: oz-qa-cluster
        region: eu-central-1
    
    # Elastic Loadbalancers
    - name: EUC1-ELB-QA-cluster
      type: loadBalancer
      versionTemplate:
        sourceName: $ARN
        method: application

   #### INTEGRATIONS ####
    - name: aws-CIS-Integration
      type: integration
      integration: AWS-CIS

    - name: aws-cliConfig
      type: cliConfig
      integration: AWS-EIS
      versionTemplate:
        region: eu-west-1
        
    - name: Sonar
      type: integration
      integration: Sonar
      
    - name: BRep
      type: integration
      integration: BRep

    - name: SRep
      type: integration
      integration: SRep
      
    - name: RunMode
      type: integration
      integration: RunMode
      
    #### NOTIFICATIONS ####
    - name: Slack
      type: notification
      integration: Slack
      versionTemplate:
        recipients:
            - "#jdemo"

#### END RESOURCES CONFIG

#### JOBS CONFIG (GLOBAL ACROSS SUBSCRIPTION)
# ****************************************************************************************************************
# * Build Release branch after successful merge from Development branch                                          *
# *                    ------------- Then ------------------------------>                                        *
# *                                   A. Create a Manifest                                                       *
# *                                   B. setup Staging environment                                               *
# *                                   ------------- Then ------------------------------>                         *
# *                                                 C. Deploy Image                                              *
# *                                                 D. Run QA tests                                              *
# *                                                 E. Merge Release branch into Master branch                   *
# *                                                 ------------- Then ------------------------------>           *
# *                                                               F. Build Master branch                         *
# *                                                               G. Publish to DockerHub after successful build *
# ****************************************************************************************************************

jobs:
    # ****************************************************************************************************************
    # * Build Release branch after successful merge from Development branch                                          *
    # *                    ------------- Then ------------------------------>                                        *
    # *                                   A. Create a Manifest                                                       *
    # *                                   B. setup Staging environment                                               *
    # ****************************************************************************************************************
    - name: jdemo_runCI
      type: runCI
      steps:
        - IN: RunMode
        - IN: CI_CONTAINER
        - IN: CI_CONTAINER_VERSION
        - IN: IMAGE
        - IN: IMAGE_VERSION
        - OUT: jdemoImg
        - OUT: jdemoImgQA
        
    - name: jdemoManifest
      type: manifest
      dependencyMode: strict   # optional
      flags:
        - jdemo
      steps:
        - IN: jdemoImg
        - IN: dockerOptions
        - IN: replicas

    - name: jdemoManifestQA
      type: manifest
      dependencyMode: strict   # optional
      flags:
        - jdemo
      steps:
        - IN: jdemoImgQA
        - IN: dockerOptions
        - IN: replicas
        
    - name: configureStagingEnvironment
      type: runSh
      triggerMode: serial
      dependencyMode: strict   # optional
      steps:
        - IN: RunMode
        - IN: jdemoImgQA
        - IN: CI_CONTAINER
        - IN: CI_CONTAINER_VERSION
        - IN: Sonar
        - IN: BRep
        - IN: SRep
        - IN: IMAGE
        - IN: IMAGE_VERSION
        - IN: scripts-from-srcRepo
        - IN: aws-cliConfig
          scopes:
            - ecr
        - TASK:
            name: pullPrivateImage
            script:
              - printenv
              - docker pull $CI_CONTAINER:$CI_CONTAINER_VERSION
        - TASK:
            name: setupStagingEnvironment
            runtime:                  # optional
              options:
                imageName: $CI_CONTAINER
                imageTag: $CI_CONTAINER_VERSION
                pull: false
                options: '--privileged=false --net=bridge -e FOO=true -e BOO=false'
            script:
              - chmod +x $SCRIPTSFROMSRCREPO_STATE/bas/scripts/shippable/*
              - $SCRIPTSFROMSRCREPO_STATE/bas/scripts/shippable/setupStagingEnvironment.sh 
                  -src "$SCRIPTSFROMSRCREPO_STATE/src/main/"
                  -w "$SCRIPTSFROMSRCREPO_STATE/tf-temp"
                  -m terraform
                  -lb EUC1-ELB-QA-cluster
                  -ak "$AWSCLICONFIG_INTEGRATION_ACCESSKEY"
                  -sk "$AWSCLICONFIG_INTEGRATION_SECRETKEY"
                  "$DEBUG"
      on_failure:
        - NOTIFY: Slack

     # ****************************************************************************************************************
     # *                                   ------------- Then ------------------------------>                         *
     # *                                                 C. Deploy Image                                              *
     # *                                                 D. Run QA tests                                              *
     # *                                                 E. Merge Release branch into Master branch                   *
     # ****************************************************************************************************************
    - name: deployImage-EUC1
      type: deploy
      dependencyMode: strict   # optional
      method: replace
      flags:
       - jdemo
      steps: 
        - IN: jdemoManifestQA    # manifest
        - IN: configureStagingEnvironment
        - IN: EUC1-QA-cluster
        - IN: EUC1-ELB-QA-cluster
          applyTo:
            - manifest: jdemoManifestQA
              image: jdemoImgQA
              port: 8080
      on_failure:
        - NOTIFY: Slack

    - name: genericRunQATests
      type: runSh
      dependencyMode: strict   # optional
      on_start:
        - NOTIFY: Slack
      steps:
        - IN: RunMode
        - IN: deployImage-EUC1
          switch: off
        - IN: CI_CONTAINER
        - IN: CI_CONTAINER_VERSION
        - IN: Sonar
        - IN: BRep
        - IN: SRep
        - IN: IMAGE
        - IN: IMAGE_VERSION
        - IN: scripts-from-srcRepo
        - IN: aws-cliConfig
          scopes:
            - ecr
        - TASK:
            name: pullPrivateImage
            script:
              - docker pull $CI_CONTAINER:$CI_CONTAINER_VERSION
        - TASK:
            name: runQATests
            runtime:                  # optional
              options:
                imageName: $CI_CONTAINER
                imageTag: $CI_CONTAINER_VERSION
                pull: false
                options: '--privileged=false --net=bridge -e FOO=true -e BOO=false'
            script:
              - echo "=== list of envs ====" && printenv
              - chmod +x $SCRIPTSFROMSRCREPO_STATE/bas/scripts/shippable/*
              - $SCRIPTSFROMSRCREPO_STATE/bas/scripts/shippable/prepare.sh
                   -src $SHIPPABLE_REPO_DIR/bas/resources/gradle/gradle.properties
                   $DEBUG
              - $SCRIPTSFROMSRCREPO_STATE/bas/scripts/shippable/approval.sh
                   $DEBUG
      on_failure:
        - NOTIFY: Slack

    - name: verify
      type: runSh
      dependencyMode: strict   # optional
      on_start:
        - NOTIFY: Slack
      steps:
        - IN: jdemoManifest
          switch: off
        - IN: aws-cliConfig
          scopes:
            - ecr
        - TASK:
            name: pullCustomImage
            script:
              #- docker pull $CI_CONTAINER:$CI_CONTAINER_VERSION
              - docker pull drydock/u16javall:v6.1.4
        - TASK:
            name: checkHealth
            runtime:                  # optional
              options:
                #imageName: $CI_CONTAINER
                imageName: drydock/u16javall
                imageTag: 'v6.1.4' #'1.0'
                pull: false
                options: '--privileged=false --net=bridge -e FOO=true -e BOO=false'
            script:
              - echo "==== TODO TODO TODO TODO ===="
      on_failure:
        - NOTIFY: Slack
        
#### END JOBS CONFIG